services:
  ticket-frontend:
    build:
      context: ./ticket-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./ticket-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true